"""Anime and manga headlines for September 2026.

Summaries are written for this hub. Each item links to the report it came from.
This is a curated desk, not every story published that month.
"""

NEWS = [
    {
        "date": "2026-09-23",
        "world": "anime",
        "title": "From Old Country Bumpkin to Master Swordsman gets a third season",
        "summary": "The anime's site announced a third season the day after season two ended, and posted a new visual.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-23",
    },
    {
        "date": "2026-09-23",
        "world": "anime",
        "title": "Summer 2026's standouts include Ghost in the Shell and Goodbye, Lara",
        "summary": "Anime News Network's seasonal roundup names Science SARU's The Ghost in the Shell, Jaadugar: A Witch in Mongolia, and Kinema Citrus' Goodbye, Lara among the season's strongest shows.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-23",
    },
    {
        "date": "2026-09-22",
        "world": "anime",
        "title": "Cyberpunk: Edgerunners 2 teases an escape from Arasaka",
        "summary": "A new video for the sequel series focuses on getting out of Arasaka.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-22",
    },
    {
        "date": "2026-09-22",
        "world": "manga",
        "title": "Manga Plus adds KAKAKAKA, The Ura Files, and Noisering",
        "summary": "The Shueisha app listed those three series plus one more title.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-22",
    },
    {
        "date": "2026-09-22",
        "world": "manga",
        "title": "Magilumiere and Ya Boy Kongming! creators start new manga",
        "summary": "Yū Aoki and Yuto Yotsuba each launched a new series.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-22",
    },
    {
        "date": "2026-09-22",
        "world": "manga",
        "title": "Higure Sakino starts a new manga",
        "summary": "The creator of Emma and the Eyes that Bid Farewell has a new serialization.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-22",
    },
    {
        "date": "2026-09-22",
        "world": "manga",
        "title": "Yu Hibari's novels are getting a manga",
        "summary": "Watashi de Dōtei Suteta Kuse ni is moving from novels into manga.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-22",
    },
    {
        "date": "2026-09-22",
        "world": "manga",
        "title": "Tapas, Kakao's North American webtoon app, is shutting down",
        "summary": "Kakao Entertainment is closing the Tapas platform in North America.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-22",
    },
    {
        "date": "2026-09-22",
        "world": "anime",
        "title": "Super Psychic Policeman Chojo shows its theme songs",
        "summary": "A second promo video names the songs for the series.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-22",
    },
    {
        "date": "2026-09-22",
        "world": "anime",
        "title": "Ani-One Asia picks up three more series",
        "summary": "The licensor added Iceblade Sorcerer season two, Reborn as a Goblin, and Laid-Off Cheat-Granting Mage.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-22",
    },
    {
        "date": "2026-09-21",
        "world": "anime",
        "title": "Grand Blue Dreaming is coming back for season four",
        "summary": "The announcement landed the day after season three's finale. That season opened in July and was set in Palau.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-21",
    },
    {
        "date": "2026-09-20",
        "world": "anime",
        "title": "Magic Knight Rayearth returns as a two-season TV anime",
        "summary": "CLAMP's manga gets a new series from October 7 on TV Asahi, directed by Sunghoo Park. Tomiaki sings the opening, Kawaguchi Yurina the ending. It is the first new Rayearth anime in about 29 years.",
        "source": "Mantanweb",
        "url": "https://en.mantan-web.jp/e_article/20260917dog00m200019000a.html",
    },
    {
        "date": "2026-09-19",
        "world": "anime",
        "title": "Daemons of the Shadow Realm is renewed",
        "summary": "Hiromu Arakawa's Yomi no Tsugai anime will get a second season. The staff announced it after the first season's second part ended.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-19/daemons-of-the-shadow-realm-anime-gets-2nd-season/.241990",
    },
    {
        "date": "2026-09-14",
        "world": "anime",
        "title": "If It's a Conflict, Leave it to Hatta is becoming a TV anime",
        "summary": "Kodansha's Morning magazine confirmed an adaptation of Motohiro Den's geopolitical manga. More details are still to come.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "anime",
        "title": "The Fable season two is set for January 2027",
        "summary": "A new trailer gives the second season a January 2027 premiere.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "anime",
        "title": "Ranma 1/2 season three has a third promo",
        "summary": "The new television anime posted another preview for its third season.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "anime",
        "title": "A new Sgt. Frog series shows theme songs and five more cast members",
        "summary": "The second main trailer for the new TV anime names the songs and adds five voices.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "anime",
        "title": "Hello, I Am a Witch debuts on October 5",
        "summary": "A new video adds cast, staff, and theme songs for the love-potion series, with an October 5 start.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "anime",
        "title": "The Ramparts of Ice season two previews its opening",
        "summary": "A second promo plays the opening theme for the new season.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "anime",
        "title": "The next Doraemon film opens in Japan on March 5, 2027",
        "summary": "A teaser gives the 2027 movie its Japanese opening date.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "anime",
        "title": "The latest Crayon Shin-chan film is the franchise's biggest",
        "summary": "The current movie is now the highest-grossing Crayon Shin-chan film. It opens in Malaysia on October 22.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "anime",
        "title": "Whisper of the Heart returns to UK cinemas",
        "summary": "The Studio Ghibli film opened in British cinemas the week of September 14.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "anime",
        "title": "The Chiikawa film opens in the Philippines on September 30",
        "summary": "The anime movie has a Philippine release date at the end of the month.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "manga",
        "title": "Silent Hill f is getting a manga about Fox Mask",
        "summary": "A manga based on the game's Fox Mask character was announced.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "manga",
        "title": "New manga from Arata Aki and Atsushi Kaneko",
        "summary": "Aki launched Enma Note, a demon-idol manga. Kaneko launched MISH/MASH.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "manga",
        "title": "Lycoris Recoil's manga is two chapters from the end",
        "summary": "The adaptation will finish in two chapters. Suikoden Star Leap's manga has already ended, and Even a Replica Can Fall in Love closes with volume 7.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "manga",
        "title": "Ushijima the Loan Shark returns for a one-shot",
        "summary": "The new chapter is set ten years after the manga ended.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-14",
        "world": "manga",
        "title": "Kodansha will name its first Indian-printed manga in early October",
        "summary": "The publisher said the first lineup of manga printed in India arrives in early October 2026.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-14",
    },
    {
        "date": "2026-09-12",
        "world": "manga",
        "title": "Orb creator Uoto has two new manga on the way",
        "summary": "Hallucination Meat is headed for Weekly Big Comic Spirits. Uoto is also working with Kyō Yoneshiro on Test Taker/Cheaters.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-12",
    },
    {
        "date": "2026-09-02",
        "world": "anime",
        "title": "Nippon Sangoku is getting a sequel",
        "summary": "Twin Engine confirmed a follow-up to The Three Nations of the Crimson Sun and posted an announcement video. No further details yet.",
        "source": "Anime News Network",
        "url": "https://www.animenewsnetwork.com/news/2026-09-02/nippon-sangoku-anime-gets-sequel/.241284",
    },
]


def news_items(world=None):
    items = NEWS
    if world in {"anime", "manga"}:
        items = [item for item in items if item["world"] == world]
    return items
